[package]
name = "cogn"
version = "0.1.0"
edition = "2018"
description = "Accelerated machine learning in Rust."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.5.0"
egg = "0.6.0"
spaces = "5.0.0"
